version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: thisisapassword1234
      POSTGRES_DB: django
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
