version: '3'

services:
  django:
    build: .
    environment:
      DJANGO_DEBUG: 'TRUE'
      DJANGO_MANAGEPY_MIGRATE: 'TRUE'
      DJANGO_MANAGEPY_COLLECTSTATIC: 'TRUE'
      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app

  postgres:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: django
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
