version: '3'

services:
  web:
    image: tyh835/simple_stickies_nginx:1.2
    depends_on:
      - django
    ports:
      - 8000:80
    volumes:
      - static:/usr/share/nginx/static

  django:
    image: tyh835/simple_stickies:1.4
    environment:
      DJANGO_DEBUG: 'FALSE'
      DJANGO_MANAGEPY_MIGRATE: 'TRUE'
      DJANGO_MANAGEPY_COLLECTSTATIC: 'TRUE'
      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - static:/usr/src/app/static

  postgres:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: django
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  static:
  postgres:
