version: '3'

# This docker-compose file is strictly used for running tests
services:
  django_test:
    build: .
    environment:
      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
      DJANGO_DEBUG: 'True'
      DJANGO_MANAGEPY_MIGRATE: 'True'
      DJANGO_MANAGEPY_COLLECTSTATIC: 'True'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    command: python manage.py test

  postgres:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: django
    ports:
      - 5432:5432
    volumes:
      - testdb:/var/lib/postgresql/data

volumes:
  testdb:
