# Generated by Django 2.1.5 on 2019-02-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('positionX', models.IntegerField(default=16)),
                ('positionY', models.IntegerField(default=16)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
