# Generated by Django 2.1.5 on 2019-02-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#fffeb7', max_length=12),
        ),
    ]
