# Generated by Django 2.1.5 on 2019-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190213_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
